In [6]:
import pandas as pd

messages = pd.read_csv(
    'SMSSpamCollection.txt',
    sep='\t',
    header=None,
    names=['label', 'message']
)

messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
##data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [8]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [9]:
corpus = []
for i in range(0, len(messages)):
    # Remove all characters except alphabets and keep spaces
    review = re.sub('[^a-zA-Z ]', ' ', messages['message'][i])
    
    review = review.lower()
    review = review.split()
    # Remove stopwords and apply stemming
    review = [lemmatizer.lemmatize(word , pos='v') for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [10]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promise wont take help grant fulfil promise wonderful bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goals team news txt ur national team eg england try wales scotland txt poboxox w wq',
 'seriously spell name',
 'go try months ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'force eat slice really hungry tho suck mark get worry know sick turn pizza lol',
 'lol always convince',
 'catch bus fry egg make tea eat mom leave dinner feel love',
 'back amp pack car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live us',
 'yeah get v apologetic n fall actin like spoil child get catch till go badly cheer',
 'k tell anything',
 'fear faint housework quick cuppa',
 'thank subscription ringtone uk mobile charge month please confirm reply yes reply charge',
 'yup ok go home look timings msg xuhui go learn nd may lesson',
 'oops let know roommate do',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decide anything tomo try invite anything',
 'pls go ahead watts want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg try call reply sms free nokia mobile free camcorder please call delivery tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call message miss call',
 'get hep b immunisation nigeria',
 'fair enough anything go',
 'yeah hopefully tyler could maybe ask around bite',
 'u know stubborn even want go hospital keep tell mark weak sucker hospitals weak suckers',
 'think first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crash place tonight',
 'wow never realize embarassed accomodations think like since best could always seem happy cave sorry give sorry offer sorry room embarassing',
 'sms ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pass call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meet',
 'tell reach',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girls situation seekers',
 'part check iq',
 'sorry roommates take forever ok come',
 'ok lar double check wif da hair dresser already say wun cut v short say cut look nice',
 'value customer please advise follow recent review mob award bonus prize call',
 'today song dedicate day song u dedicate send ur valuable frnds first rply',
 'urgent ur award complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt ls aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finish class',
 'hi babe im home wanna something xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still look job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sms',
 'real u get yo need ticket one jacket do already use multis',
 'yes start send request make pain come back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spend late afternoon casualty mean do stuff moro include time sheet sorry',
 'smile pleasure smile pain smile trouble pour like rain smile sum hurt u smile becoz someone still love see u smile',
 'please call customer service representative pm guarantee cash prize',
 'havent plan buy later check already lido get show e afternoon u finish work already',
 'free ringtone wait collect simply text password mix verify get usher britney fml po box mk h ppw',
 'watch telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bite run forget hairdressers appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x ams xx',
 'still look car buy go drive test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'wow right mean guess give boston men change search location nyc something change cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truly memorable',
 'aight hit get cash',
 'would ip address test consider computer minecraft server',
 'know grumpy old people mom like better lie always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'go dinner msg',
 'ok wif cos like try new things scar u dun like mah cos u say loud',
 'gent try contact last weekend draw show prize guarantee call claim code k valid hrs ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa say happy b day boss felt special askd lunch lunch invite apartment go',
 'winner u specially select receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla need',
 'hmm uncle inform pay school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expire',
 'urgent mobile award bonus caller prize final try contact u call landline box wr c ppm',
 'new address apples pair malarky',
 'todays voda number end select receive award match please call quote claim code standard rat app',
 'go sao mu today do',
 'predict wat time finish buy',
 'good stuff',
 'know yetunde send money yet send text bother send dont involve anything impose anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get lay tonight want real dog locations send direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activities',
 'rcv msgs chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'get c lazy type forget lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt think nver get tire little things lovable persons coz somtimes little things occupy biggest part hearts gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name take class us',
 'freemsg reply text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k delete contact',
 'sindu get job birla soft',
 'wine flow nevering',
 'yup thk cine better cos need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'everywhere dirt floor windows even shirt sometimes open mouth come flow dream world without half chores time joy lot tv show see guess like things must exist like rain hail mist time do become one',
 'aaooooright work',
 'leave house',
 'hello love get interview today happy good boy think miss',
 'customer service annoncement new years delivery wait please call arrange delivery',
 'winner u specially select receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excite day spend make happy',
 'pls stop bootydelious f invite friend reply yes see www sms ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent try contact last weekend draw show prize guarantee call claim code valid hrs',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure get time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloody hell cant believe forget surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know get money carlos make call',
 'u still go mall',
 'turn friends stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi speak maneesha v like know satisfy experience reply toll free yes',
 'lift hop offer money need especially end month approach hurt study anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'go nothing great bye',
 'hello handsome find job lazy work towards get back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guarantee cash prize',
 'get xmas radio time get',
 'jus reach home go bathe first sis use net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry join league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally complete course',
 'stop however suggest stay someone able give ors every stool',
 'hope settle new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u get persons story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bite bloody babyjontet txt back u xxx',
 'find enc lt gt',
 'send lt gt buck',
 'hello darlin ive finish college txt u finish u love kate xxx',
 'account refill successfully inr lt decimal gt keralacircle prepay account balance rs lt decimal gt transaction id kr lt gt',
 'goodmorning sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa say happy b day boss felt special askd lunch lunch invite apartment go',
 'aight yo dats straight dogg',
 'please give us connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break reward semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match head towards draw prediction',
 'tire sleep well past nights',
 'easy ah sen get select mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bite lor thk e nite scenery nice leh',
 'new mobiles must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lessons happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorry battery die yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight pence',
 'print oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation lose person dont argue ur friends kick amp say always correct',
 'u secret admirer look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeeee tel v avent do sportsx',
 'okay shin mean sign sound better',
 'although tell u dat baig face watch really like e watch u give cos fr u thanx everything dat u do today touch',
 'u remember old commercial',
 'late say website dont slippers',
 'ask call ok',
 'kallis wont bat nd innings',
 'didnt work oh ok goodnight fix ready time wake dearly miss good night sleep',
 'congratulations ur award cd vouchers gift guarantee free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way show deep affection care n luv kettoda manda nice day da',
 '',
 'up days also ship company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect do get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'try contact reply offer video handset anytime network mins unlimited text camcorder reply call',
 'park next mini come today think',
 'yup',
 'anyway go shop cos sis do yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charge pm unsubscribe text stop',
 'dint come us',
 'wana plan trip sometme',
 'sure yet still try get hold',
 'ur ringtone service change free credit go club mobiles com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sort narcotics situation',
 'night end another day morning come special way may smile like sunny ray leave worry blue blue bay',
 'hmv bonus special pound genuine hmv vouchers answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bite',
 'send type food like',
 'do hand celebrations full swing yet',
 'get call tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok ask money far',
 'okie',
 'yeah think usual guy still pass last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friends call world ge',
 'dear shall mail tonite busy street shall update tonite things look ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey tell name gautham ah',
 'haf u find feel stupid da v cam work',
 'oops get bite',
 'much buzy',
 'accidentally delete message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rise grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time get somebody high first time diesel v',
 'shit really shock scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sms ac blind date u rodds aberdeen unite kingdom check http img sms ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hang thread cause u buy stuff',
 'themob check newest selection content game tone gossip babes sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play cs winnersclub po box uz gbp week',
 'say give call friend get money definitely buy end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lose',
 'make day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk get lo oso forget liao',
 'really dude friends afraid',
 'december mobile mths entitle update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bite l cos bus hav gon past cos full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message miss call',
 'hi da todays class',
 'say good sign well know track record read women',
 'cool text park',
 'read text send mean joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany pence per minute call fix line via access number prepayment direct access',
 'chance might evaporate soon violate privacy steal phone number employer paperwork cool please contact report supervisor',
 'valentines day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent win din',
 'sleep surf',
 'sorry call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must texts happy read one wiv hello caroline end favourite bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnite tc practice go',
 'dis yijue jus saw ur mail case huiming havent send u num dis num',
 'one small prestige problem',
 'fancy shag interest sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'check really miss see jeremiah great month',
 'nah help never iphone',
 'car hour half go apeshit',
 'today sorry day ever angry ever misbehave hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay try figure much safely spend weed',
 'lt gt ish minutes minutes ago wtf',
 'thank call forget say happy onam sirji fine remember meet insurance person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratulations ur award cd vouchers gift guarantee free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',
 'actor work work even sleep late since unemployed moment always sleep late unemployed every day saturday',
 'hello get st andrews boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey status right',
 'busy try finish new year look forward finally meet',
 'good afternoon sunshine dawn day refresh happy alive breathe air smile think love always',

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=2500 , binary = True ,ngram_range=(1, 2) )

In [12]:
## INDEPEMDENT feature
x  = vectorizer.fit_transform(corpus).toarray()

In [13]:
vectorizer.vocabulary_

{'go': 813,
 'point': 1611,
 'crazy': 450,
 'available': 113,
 'bugis': 221,
 'great': 857,
 'world': 2434,
 'la': 1092,
 'cine': 339,
 'get': 767,
 'wat': 2343,
 'ok': 1477,
 'lar': 1102,
 'joke': 1059,
 'wif': 2399,
 'ok lar': 1480,
 'free': 714,
 'entry': 605,
 'wkly': 2422,
 'comp': 397,
 'win': 2404,
 'cup': 465,
 'final': 680,
 'st': 1966,
 'may': 1265,
 'text': 2085,
 'receive': 1712,
 'question': 1671,
 'std': 1981,
 'txt': 2200,
 'rate': 1689,
 'apply': 82,
 'free entry': 719,
 'entry wkly': 607,
 'std txt': 1982,
 'txt rate': 2207,
 'rate apply': 1690,
 'dun': 564,
 'say': 1796,
 'early': 571,
 'already': 51,
 'nah': 1387,
 'think': 2107,
 'usf': 2278,
 'live': 1165,
 'around': 92,
 'though': 2116,
 'think go': 2110,
 'freemsg': 727,
 'hey': 916,
 'darling': 483,
 'week': 2369,
 'word': 2430,
 'back': 132,
 'like': 1152,
 'fun': 745,
 'still': 1985,
 'xxx': 2463,
 'send': 1829,
 'even': 614,
 'brother': 213,
 'speak': 1947,
 'treat': 2175,
 'per': 1545,
 'request': 1744,
 'set': 1848,
 'callertune': 269,
 'callers': 267,
 'press': 1635,
 'copy': 432,
 'friends': 734,
 'per request': 1550,
 'set callertune': 1849,
 'callertune callers': 270,
 'callers press': 268,
 'press copy': 1636,
 'copy friends': 433,
 'friends callertune': 735,
 'winner': 2409,
 'value': 2287,
 'network': 1407,
 'customer': 471,
 'select': 1822,
 'prize': 1644,
 'reward': 1755,
 'claim': 342,
 'call': 239,
 'code': 362,
 'valid': 2285,
 'hours': 971,
 'claim call': 343,
 'call claim': 243,
 'claim code': 344,
 'mobile': 1323,
 'months': 1345,
 'entitle': 603,
 'update': 2241,
 'latest': 1112,
 'colour': 377,
 'mobiles': 1333,
 'camera': 273,
 'co': 359,
 'entitle update': 604,
 'update latest': 2243,
 'latest colour': 1114,
 'free call': 717,
 'call mobile': 253,
 'mobile update': 1331,
 'update co': 2242,
 'co free': 360,
 'gonna': 838,
 'home': 946,
 'soon': 1937,
 'want': 2330,
 'talk': 2063,
 'stuff': 2014,
 'anymore': 70,
 'tonight': 2157,
 'cry': 457,
 'enough': 600,
 'today': 2141,
 'want talk': 2339,
 'six': 1898,
 'chance': 311,
 'cash': 291,
 'pound': 1623,
 'cost': 436,
 'day': 488,
 'days': 494,
 'reply': 1734,
 'hl': 933,
 'info': 1018,
 'chance win': 313,
 'win cash': 2405,
 'reply hl': 1736,
 'hl info': 934,
 'urgent': 2267,
 'membership': 1281,
 'www': 2451,
 'net': 1405,
 'pobox': 1607,
 'ldnw': 1126,
 'week free': 2371,
 'txt word': 2209,
 'search': 1809,
 'right': 1757,
 'thank': 2096,
 'promise': 1658,
 'wont': 2429,
 'take': 2059,
 'help': 914,
 'wonderful': 2428,
 'bless': 178,
 'time': 2126,
 'date': 486,
 'sunday': 2029,
 'use': 2276,
 'credit': 452,
 'click': 355,
 'wap': 2340,
 'link': 1161,
 'next': 1421,
 'message': 1287,
 'http': 981,
 'com': 380,
 'oh': 1472,
 'watch': 2347,
 'eh': 582,
 'remember': 1728,
 'spell': 1958,
 'name': 1389,
 'yes': 2483,
 'naughty': 1397,
 'make': 1237,
 'wet': 2388,
 'fine': 688,
 'way': 2353,
 'feel': 665,
 'england': 596,
 'dont': 544,
 'miss': 1311,
 'team': 2070,
 'news': 1420,
 'ur': 2244,
 'national': 1393,
 'eg': 580,
 'try': 2183,
 'wq': 2445,
 'dont miss': 546,
 'seriously': 1844,
 'ha': 886,
 'ha ha': 887,
 'pay': 1541,
 'first': 693,
 'da': 476,
 'stock': 1990,
 'comin': 395,
 'aft': 25,
 'finish': 691,
 'lunch': 1227,
 'str': 2009,
 'lor': 1193,
 'ard': 86,
 'smth': 1917,
 'alright': 52,
 'meet': 1273,
 'eat': 575,
 'really': 1707,
 'hungry': 986,
 'tho': 2115,
 'suck': 2023,
 'mark': 1248,
 'worry': 2436,
 'know': 1087,
 'sick': 1875,
 'turn': 2195,
 'pizza': 1579,
 'lol': 1180,
 'always': 55,
 'catch': 300,
 'bus': 225,
 'egg': 581,
 'tea': 2068,
 'mom': 1338,
 'leave': 1130,
 'dinner': 527,
 'love': 1201,
 'amp': 58,
 'pack': 1524,
 'car': 283,
 'let': 1140,
 'room': 1771,
 'let know': 1141,
 'work': 2431,
 'feel like': 669,
 'wait': 2314,
 'clear': 354,
 'sure': 2041,
 'us': 2275,
 'yeah': 2473,
 'fall': 645,
 'spoil': 1963,
 'child': 330,
 'till': 2125,
 'cheer': 327,
 'yeah get': 2474,
 'tell': 2075,
 'anything': 72,
 'tell anything': 2076,
 'quick': 1672,
 'subscription': 2022,
 'ringtone': 1760,
 'uk': 2222,
 'charge': 317,
 'month': 1344,
 'please': 1586,
 'confirm': 411,
 'mobile charge': 1325,
 'reply yes': 1739,
 'yup': 2498,
 'look': 1189,
 'msg': 1368,
 'learn': 1128,
 'nd': 1398,
 'lesson': 1138,
 'ok go': 1479,
 'go home': 822,
 'oops': 1503,
 'roommate': 1772,
 'do': 538,
 'see': 1817,
 'letter': 1142,
 'decide': 502,
 'anything lor': 73,
 'hello': 913,
 'saturday': 1790,
 'texting': 2092,
 'tomo': 2149,
 'invite': 1030,
 'pls': 1591,
 'ahead': 33,
 'weekend': 2375,
 'abiola': 1,
 'great weekend': 859,
 'forget': 708,
 'need': 1402,
 'crave': 449,
 'sweet': 2051,
 'want need': 2335,
 'burn': 224,
 'sms': 1915,
 'nokia': 1434,
 'camcorder': 271,
 'delivery': 511,
 'tomorrow': 2150,
 'try call': 2184,
 'call reply': 258,
 'nokia mobile': 1438,
 'mobile free': 1328,
 'free camcorder': 718,
 'please call': 1587,
 'delivery tomorrow': 512,
 'hope': 953,
 'man': 1241,
 'well': 2383,
 'lt': 1218,
 'gt': 865,
 'inch': 1012,
 'lt gt': 1220,
 'miss call': 1314,
 'nigeria': 1426,
 'hopefully': 962,
 'tyler': 2217,
 'could': 441,
 'maybe': 1268,
 'ask': 99,
 'bite': 175,
 'hospital': 965,
 'keep': 1073,
 'want go': 2333,
 'saw': 1795,
 'class': 352,
 'first time': 694,
 'usually': 2280,
 'run': 1780,
 'half': 892,
 'almost': 49,
 'whole': 2396,
 'second': 1812,
 'like lt': 1155,
 'fyi': 748,
 'ride': 1756,
 'morning': 1350,
 'place': 1580,
 'wow': 2444,
 'never': 1411,
 'realize': 1706,
 'since': 1886,
 'best': 161,
 'seem': 1821,
 'happy': 900,
 'sorry': 1938,
 'give': 805,
 'offer': 1467,
 'ac': 4,
 'new': 1412,
 'red': 1717,
 'play': 1582,
 'ice': 993,
 'correct': 434,
 'end': 589,
 'sms ac': 1916,
 'yesterday': 2488,
 'find': 683,
 'congrats': 412,
 'year': 2478,
 'special': 1950,
 'cinema': 340,
 'pass': 1538,
 'etc': 610,
 'bx': 230,
 'ip': 1034,
 'pm': 1601,
 'etc free': 611,
 'bx ip': 231,
 'ip pm': 1035,
 'later': 1109,
 'sorry call': 1939,
 'call later': 251,
 'later meet': 1110,
 'reach': 1698,
 'pick': 1570,
 'move': 1359,
 'pain': 1527,
 'kill': 1081,
 'way home': 2356,
 'good': 840,
 'girls': 803,
 'situation': 1897,
 'part': 1534,
 'check': 326,
 'iq': 1038,
 'forever': 707,
 'come': 383,
 'ok come': 1478,
 'double': 549,
 'hair': 891,
 'wun': 2450,
 'cut': 473,
 'short': 1867,
 'nice': 1424,
 'follow': 703,
 'review': 1754,
 'mob': 1321,
 'award': 119,
 'bonus': 186,
 'award bonus': 120,
 'prize call': 1645,
 'song': 1933,
 'frnds': 740,
 'rply': 1776,
 'send ur': 1840,
 'complimentary': 403,
 'trip': 2176,
 'dis': 531,
 'ls': 1217,
 'ur award': 2245,
 'hear': 908,
 'lucky': 1225,
 'save': 1794,
 'money': 1343,
 'hee': 911,
 'hi': 920,
 'babe': 127,
 'im': 1001,
 'wanna': 2329,
 'something': 1929,
 'xx': 2462,
 'hi babe': 921,
 'call free': 245,
 'thats': 2101,
 'cool': 430,
 'respect': 1746,
 'thats cool': 2102,
 'people': 1544,
 'much': 1375,
 'pa': 1522,
 'job': 1055,
 'ta': 2058,
 'ah': 31,
 'hi hi': 924,
 'stop': 1993,
 'urgnt': 2273,
 'real': 1705,
 'yo': 2492,
 'ticket': 2123,
 'one': 1495,
 'start': 1974,
 'bed': 152,
 'coin': 367,
 'gotta': 854,
 'pain come': 1528,
 'come back': 384,
 'kano': 1070,
 'il': 999,
 'download': 551,
 'wen': 2386,
 'wen ur': 2387,
 'stand': 1970,
 'close': 356,
 'another': 63,
 'night': 1427,
 'spend': 1959,
 'late': 1108,
 'afternoon': 26,
 'mean': 1270,
 'moro': 1355,
 'include': 1013,
 'sheet': 1860,
 'smile': 1912,
 'pleasure': 1589,
 'trouble': 2177,
 'rain': 1682,
 'sum': 2026,
 'hurt': 989,
 'someone': 1926,
 'service': 1845,
 'representative': 1741,
 'guarantee': 874,
 'call customer': 244,
 'customer service': 472,
 'service representative': 1847,
 'representative pm': 1743,
 'pm guarantee': 1603,
 'guarantee cash': 876,
 'cash prize': 297,
 'havent': 906,
 'plan': 1581,
 'buy': 228,
 'show': 1870,
 'collect': 372,
 'simply': 1885,
 'password': 1539,
 'verify': 2289,
 'po': 1605,
 'box': 196,
 'free ringtone': 723,
 'po box': 1606,
 'box mk': 199,
 'movie': 1360,
 'abt': 3,
 'wat abt': 2344,
 'load': 1169,
 'loan': 1170,
 'wk': 2420,
 'shower': 1873,
 'cause': 301,
 'prob': 1650,
 'need get': 1403,
 'get home': 776,
 'coffee': 366,
 'nothing': 1451,
 'else': 585,
 'okay': 1490,
 'price': 1638,
 'long': 1185,
 'ave': 114,
 'drive': 559,
 'test': 2084,
 'yet': 2489,
 'guess': 882,
 'men': 1282,
 'change': 314,
 'cuz': 475,
 'page': 1526,
 'umma': 2225,
 'life': 1147,
 'lot': 1196,
 'dear': 498,
 'love lot': 1207,
 'wish': 2411,
 'birthday': 171,
 'truly': 2179,
 'aight': 35,
 'hit': 931,
 'get cash': 771,
 'would': 2442,
 'address': 18,
 'consider': 418,
 'computer': 404,
 'old': 1492,
 'better': 164,
 'lie': 1146,
 'busy': 227,
 'research': 1745,
 'go dinner': 819,
 'cos': 435,
 'things': 2106,
 'scar': 1803,
 'mah': 1233,
 'contact': 419,
 'last': 1103,
 'draw': 552,
 'hrs': 979,
 'ppm': 1628,
 'try contact': 2185,
 'contact last': 423,
 'last weekend': 1107,
 'weekend draw': 2376,
 'draw show': 554,
 'show prize': 1871,
 'prize guarantee': 1647,
 'guarantee call': 875,
 'code valid': 365,
 'valid hrs': 2286,
 'hrs ppm': 980,
 'wa': 2313,
 'anyway': 76,
 'juz': 1068,
 'eatin': 576,
 'weight': 2381,
 'haha': 889,
 'happen': 898,
 'enter': 601,
 'cabin': 233,
 'boss': 191,
 'felt': 670,
 'askd': 100,
 'apartment': 79,
 'enter cabin': 602,
 'cabin pa': 234,
 'pa say': 1523,
 'say happy': 1798,
 'happy day': 902,
 'day boss': 489,
 'boss felt': 192,
 'felt special': 671,
 'special askd': 1951,
 'askd lunch': 101,
 'lunch lunch': 1229,
 'lunch invite': 1228,
 'invite apartment': 1031,
 'apartment go': 80,
 'specially': 1955,
 'holiday': 942,
 'flight': 699,
 'inc': 1010,
 'operator': 1505,
 'min': 1292,
 'winner specially': 2410,
 'specially select': 1956,
 'select receive': 1823,
 'inc speak': 1011,
 'speak live': 1948,
 'live operator': 1167,
 'operator claim': 1506,
 'must': 1384,
 'friday': 731,
 'hmm': 936,
 'uncle': 2229,
 'inform': 1019,
 'school': 1805,
 'directly': 530,
 'food': 705,
 'private': 1642,
 'account': 8,
 'statement': 1977,
 'identifier': 996,
 'expire': 636,
 'private account': 1643,
 'account statement': 9,
 'statement show': 1978,
 'call identifier': 247,
 'identifier code': 997,
 'code expire': 363,
 'caller': 265,
 'landline': 1098,
 'urgent mobile': 2270,
 'mobile award': 1324,
 'bonus caller': 187,
 'caller prize': 266,
 'contact call': 420,
 'call landline': 250,
 'todays': 2145,
 'voda': 2302,
 'number': 1458,
 'match': 1255,
 'quote': 1677,
 'standard': 1971,
 'rat': 1686,
 'app': 81,
 'todays voda': 2147,
 'voda number': 2303,
 'number end': 1460,
 'end select': 591,
 'receive award': 1713,
 'match please': 1256,
 'call quote': 257,
 'quote claim': 1678,
 'code standard': 364,
 'standard rat': 1972,
 'rat app': 1687,
 'mu': 1374,
 'wat time': 2345,
 'time finish': 2128,
 'bother': 193,
 'send text': 1839,
 'girl': 802,
 'del': 507,
 'bak': 135,
 'long time': 1187,
 'give call': 806,
 'dear call': 499,
 'answer': 68,
 'sunshine': 2033,
 'quiz': 1675,
 'top': 2159,
 'sony': 1934,
 'dvd': 569,
 'player': 1584,
 'country': 442,
 'ansr': 66,
 'sp': 1945,
 'tyrone': 2220,
 'sunshine quiz': 2034,
 'quiz wkly': 1676,
 'top sony': 2160,
 'sony dvd': 1935,
 'txt ansr': 2201,
 'ansr sp': 67,
 'lay': 1121,
 'dog': 541,
 'locations': 1173,
 'direct': 529,
 'join': 1057,
 'bt': 215,
 'txting': 2214,
 'nt': 1453,
 'ec': 577,
 'want get': 2332,
 'get lay': 778,
 'locations send': 1174,
 'send direct': 1830,
 'ur mob': 2258,
 'join uk': 1058,
 'haf': 888,
 'yijue': 2490,
 'msgs': 1371,
 'chat': 321,
 'age': 29,
 'yr': 2495,
 'go get': 820,
 'lazy': 1122,
 'type': 2218,
 'lect': 1132,
 'sir': 1891,
 'mail': 1235,
 'sir wait': 1892,
 'swt': 2055,
 'tire': 2134,
 'little': 1164,
 'lovable': 1198,
 'persons': 1559,
 'coz': 446,
 'gud': 877,
 'ni': 1423,
 'gud ni': 880,
 'open': 1504,
 'ya': 2466,
 'yes see': 2486,
 'whats': 2391,
 'sexy': 1852,
 'local': 1172,
 'luv': 1230,
 'ltd': 1222,
 'per msg': 1548,
 'reply stop': 1738,
 'stop end': 1996,
 'begin': 156,
 'qatar': 1666,
 'pray': 1632,
 'hard': 904,
 'delete': 509,
 'get job': 777,
 'wine': 2408,
 'thk': 2113,
 'need go': 1404,
 'shirt': 1862,
 'sometimes': 1931,
 'dream': 556,
 'without': 2418,
 'joy': 1062,
 'tv': 2196,
 'become': 151,
 'house': 972,
 'leave house': 1131,
 'interview': 1028,
 'boy': 203,
 'years': 2479,
 'arrange': 94,
 'new years': 1419,
 'receive cash': 1714,
 'cash holiday': 296,
 'safe': 1785,
 'everyone': 621,
 'miss already': 1312,
 'parent': 1530,
 'hand': 895,
 'new job': 1413,
 'excite': 630,
 'friend': 732,
 'frnd': 739,
 'invite friend': 1032,
 'friend reply': 733,
 'see www': 1820,
 'www sms': 2455,
 'stop send': 2000,
 'send stop': 1838,
 'stop frnd': 1998,
 'order': 1514,
 'content': 425,
 'goto': 853,
 'internet': 1027,
 'menu': 1283,
 'ur mobile': 2259,
 'urgent try': 2272,
 'avoid': 115,
 'wit': 2415,
 'fancy': 648,
 'completely': 402,
 'also': 54,
 'waste': 2342,
 'bank': 138,
 'hmmm': 937,
 'hop': 952,
 'muz': 1385,
 'discuss': 534,
 'liao': 1143,
 'sure get': 2042,
 'get time': 788,
 'time come': 2127,
 'come later': 387,
 'hell': 912,
 'cant': 280,
 'believe': 158,
 'mr': 1364,
 'ill': 1000,
 'bath': 142,
 'carlos': 287,
 'know get': 1089,
 'get money': 783,
 'stay': 1980,
 'til': 2124,
 'smoke': 1913,
 'worth': 2439,
 'doesnt': 540,
 'log': 1175,
 'satisfy': 1789,
 'experience': 635,
 'lift': 1148,
 'especially': 609,
 'study': 2013,
 'anyways': 78,
 'gr': 855,
 'trust': 2180,
 'guy': 884,
 'bye': 232,
 'towards': 2168,
 'boytoy': 205,
 'get back': 768,
 'awesome': 126,
 'minute': 1303,
 'freephone': 728,
 'representative freephone': 1742,
 'xmas': 2461,
 'radio': 1681,
 'time get': 2129,
 'jus': 1066,
 'bathe': 143,
 'sis': 1893,
 'reach home': 1700,
 'home go': 949,
 'unique': 2233,
 'th': 2095,
 'co uk': 361,
 'touch': 2165,
 'deal': 497,
 'personal': 1556,
 'keep touch': 1075,
 'finally': 682,
 'complete': 401,
 'course': 444,
 'however': 974,
 'able': 2,
 'every': 617,
 'settle': 1850,
 'gr day': 856,
 'mrng': 1365,
 'hav': 905,
 'gud mrng': 879,
 'nice day': 1425,
 'story': 2007,
 'persons story': 1560,
 'dead': 496,
 'tmr': 2136,
 'orchard': 1513,
 'mrt': 1366,
 'kate': 1071,
 'see tomorrow': 1819,
 'buck': 219,
 'send lt': 1835,
 'gt buck': 866,
 'darlin': 482,
 'ive': 1044,
 'college': 376,
 'love kate': 1204,
 'decimal': 503,
 'balance': 136,
 'rs': 1777,
 'transaction': 2172,
 'id': 994,
 'lt decimal': 1219,
 'decimal gt': 504,
 'rs lt': 1778,
 'goodmorning': 849,
 'sleep': 1906,
 'dat': 485,
 'oso': 1517,
 'cannot': 279,
 'oredi': 1515,
 'like dat': 1153,
 'straight': 2010,
 'connection': 417,
 'bill': 168,
 'give us': 807,
 'shoot': 1864,
 'big': 167,
 'ready': 1704,
 'get ready': 786,
 'break': 209,
 'semester': 1827,
 'hope great': 958,
 'noe': 1433,
 'leh': 1133,
 'sound': 1942,
 'head': 907,
 'past': 1540,
 'nights': 1428,
 'sleep well': 1907,
 'easy': 573,
 'sen': 1828,
 'exam': 626,
 'march': 1247,
 'atm': 106,
 'register': 1723,
 'yeah think': 2477,
 'ok prob': 1483,
 'important': 1006,
 'file': 677,
 'system': 2057,
 'shop': 1865,
 'romantic': 1770,
 'nite': 1431,
 'tc': 2067,
 'biz': 176,
 'optout': 1510,
 'gbp': 759,
 'mtmsg': 1373,
 'txt nokia': 2205,
 'appreciate': 83,
 'partner': 1536,
 'career': 286,
 'star': 1973,
 'sign': 1879,
 'company': 399,
 'bcoz': 147,
 'teach': 2069,
 'lessons': 1139,
 'good morning': 846,
 'walk': 2322,
 'cross': 454,
 'road': 1767,
 'side': 1876,
 'street': 2011,
 'battery': 144,
 'die': 521,
 'flirt': 700,
 'sam': 1788,
 'name age': 1390,
 'print': 1641,
 'bus stop': 226,
 'wil': 2402,
 'argument': 89,
 'lose': 1195,
 'person': 1554,
 'argue': 88,
 'kick': 1078,
 'person dont': 1555,
 'ur friends': 2250,
 'amp say': 59,
 'secret': 1813,
 'admirer': 19,
 'reveal': 1752,
 'secret admirer': 1814,
 'admirer look': 20,
 'look make': 1191,
 'make contact': 1238,
 'contact find': 422,
 'find reveal': 686,
 'reveal think': 1753,
 'think ur': 2111,
 'ur special': 2263,
 'special call': 1952,
 'laptop': 1101,
 'case': 290,
 'tel': 2074,
 'face': 641,
 'fr': 712,
 'thanx': 2100,
 'everything': 622,
 'website': 2365,
 'kallis': 1069,
 'didnt': 519,
 'goodnight': 851,
 'fix': 696,
 'wake': 2321,
 'oh ok': 1475,
 'good night': 847,
 'congratulations': 414,
 'cd': 304,
 'vouchers': 2310,
 'gift': 798,
 'music': 1381,
 'tncs': 2137,
 'ldew': 1123,
 'ppmx': 1629,
 'congratulations ur': 415,
 'gift guarantee': 799,
 'draw txt': 555,
 'txt music': 2204,
 'music tncs': 1383,
 'tncs www': 2138,
 'www ldew': 2454,
 'ldew com': 1124,
 'com win': 382,
 'win ppmx': 2407,
 'ppmx age': 1630,
 'cal': 238,
 'hold': 939,
 'angry': 61,
 'wid': 2397,
 'dnt': 537,
 'childish': 331,
 'true': 2178,
 'deep': 505,
 'care': 285,
 'lovable bcums': 1199,
 'childish true': 332,
 'way show': 2358,
 'luv kettoda': 1231,
 ...}

In [14]:
y = pd.get_dummies(messages['label'] ,  dtype=int)

In [15]:
y

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [16]:
y = y.iloc[:,0].values

In [17]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [18]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [19]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB()

In [20]:
spam_detect_model.fit(x_train , y_train)

MultinomialNB()

In [21]:
y_pred = spam_detect_model.predict(x_test)

In [22]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [23]:
from sklearn.metrics import accuracy_score , classification_report

In [24]:
accuracy_score(y_test , y_pred)

0.9838565022421525

In [25]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       149
           1       0.99      0.99      0.99       966

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [26]:
msg = ["Win a FREE iPhone now!"]
msg_vec = vectorizer.transform(msg)   # vectorize message
y_pred = spam_detect_model.predict(msg_vec)

if y_pred[0] == 0:
    print("Message is SPAM")
else:
    print("Message is NOT spam")

Message is SPAM

In [27]:
import pickle
with open('vectorizer.pkl','wb') as file:
    pickle.dump(vectorizer,file)

In [28]:
with open('spam_detect_model.pkl','wb') as file:
    pickle.dump(spam_detect_model,file)